#!/bin/sh

for i in specimen canevas
do
    for j in en-arborescence a-plat; do
        if [ -e "$i/$j/these.tex" ]
        then
            cd $i/$j
            if [ "$i" == "specimen" -a "$j" == "a-plat" ]
            then
                latexmk -c these &&
                latexmk -f -pdf -jobname=these -pdflatex="pdflatex %O '\RequirePackage{yathesis-demo}\input{%S}'" these.tex
            else
                latexmk these
            fi
            cd ../../
        fi
        zip -9r $i-$j.zip $i/$j/  -x@exclude.lst
        echo "# Contenu de $i-$j.zip :"
        echo "############################################################"
        zipinfo -1 $i-$j.zip
    done
done
